function cipher(word){
    word1 = word.replace(/a/gi, "z")
    word2 = word1.replace(/b/gi, "y")
    word3 = word2.replace(/c/gi, "x")
    word4 = word3.replace(/d/gi, "w")
    word5 = word4.replace(/e/gi, "v")
    word6 = word5.replace(/f/gi, "u")
    word7 = word6.replace(/g/gi, "t")
    word8 = word7.replace(/h/gi, "s")
    word9 = word8.replace(/i/gi, "r")
    word10 = word9.replace(/j/gi, "q")
    word11 = word10.replace(/k/gi, "p")
    word12 = word11.replace(/l/gi, "o")
    word13 = word12.replace(/m/gi, "n")
    word14 = word13.replace(/n/gi, "m")
    word15 = word14.replace(/o/gi, "l")
    word16 = word15.replace(/p/gi, "k")
    word17 = word16.replace(/q/gi, "j")
    word18 = word17.replace(/r/gi, "i")
    word19 = word18.replace(/s/gi, "h")
    word20 = word19.replace(/t/gi, "g")
    word21 = word20.replace(/u/gi, "f")
    word22 = word21.replace(/v/gi, "e")
    word23 = word22.replace(/w/gi, "d")
    word24 = word23.replace(/x/gi, "c")
    word25 = word24.replace(/y/gi, "b")
    word26 = word25.replace(/z/gi, "a")
    console.log(word26)
}

cipher('I wish I knew how to use Javascript proficiently.')